### PR TITLE
added fcm style dataset for c4

### PR DESCRIPTION
**Pull request by lintangsutawika**

### CODE REVIEW

**Comment by AranKomat** [comment]
@lintangsutawika Thanks for pointing that out. Apparently I made a mistake with my gin config and forgot to add my `tasks.py`, where I registered the task of causal LM on C4. Basically, instead of the usual

```
{
        "inputs": 
            seqio.Feature(
                vocabulary=t5x.data.vocab.get_default_vocabulary(mode),
                add_eos=True,
                required=False),
        "targets":
            seqio.Feature(
                vocabulary=t5x.data.vocab.get_default_vocabulary(mode),
                add_eos=True)
}
```
I used the following. So, only thing you have to specify is `TASK_FEATURE_LENGTHS={"inputs": 512, "targets": 114}`. But if you want to do MLM-LM etc, it'd be something different. I'll fix it asap (maybe not today). You can work on other components meanwhile :)
```
{
        "targets":
            seqio.Feature(
                vocabulary=t5x.data.vocab.get_default_vocabulary(mode),
                add_eos=True,
                required=False),
}
```

**Comment by AranKomat** [comment]
OK I finally fixed the scalable decoder and added Pile. I probably shouldn't have synced right away, but hopefully this is OK. I changed the style of `c4/tasks.py` in a way such that objective (e.g. CLM vs. MLM) and dataset (e.g. Pile vs. C4) are separated. This will allow various different combinations without having to write the registration for each of them. Sorry if this was confusing. I think you can implement the FCM-style training as `default_fcm_task` in `t5x/utils.py` and add the following at the end of `c4/tasks.py`:

`default_clm_task('c4_eye_fcm', c4_files, jsonl=False)`

Or maybe we should have a separate file `data/objectives.py` that store all the objectives like `default_clm_task`.

**Comment by lintangsutawika** [comment]
Thanks, I will take a look soon. 

Remind me again, we want to train a scalable decoder with FCM style as a benchmark, right?

**Comment by AranKomat** [comment]
Yeah scalable decoder with FCM is going to be used as one of the baselines. By the way, `main` branch causes an error for larger models after a number of gradient updates for an unknown reason, so I'm trying to figure out what's going on.

**Comment by lintangsutawika** [comment]
Can you share the error in a separate issue?

Also, I don't know if it's related but I had trouble once that seemed to be due to network connections between nodes.

**Comment by lintangsutawika** [comment]
Did some sanity check. The features are correct.
```
In [7]: ex['decoder_input_tokens'][:9]
Out[7]: 
array([    0,  8815,  3051,     5,   148,   131, 32099, 32099,   987],
      dtype=int32)

In [8]: ex['decoder_target_tokens'][:9]
Out[8]: array([8815, 3051,    5,  148,  131,   43,   12,  987,    5], dtype=int32)
```

**Pull request merged**
